### ISSUE TITLE
Allow for '$model->$event()' in adition to 'static function orm_notify()'

### ISSUE THREAD

**Issue by snrp** [fuel/orm#11]
This is more intuitive to use. Eg:

```
public function before_insert()
{
    $this->foo = 'bar';
}
```

as oposed to :

```
protected static $_observers = array(
    'Model_Comment' => array('before_insert'),
);

public static function orm_notify($model, $event)
{
    if ($event === 'before_insert')
        $model->foo = 'bar';
}
```

It only needs a small adition to work like this. Eg: add this at the bottom of observe() in `Orm\Model`:

```
    if (method_exists($this, $event))
    {
        $this->{$event}();
    }
```

**Comment by jschreuder** [comment]
No, we decided to implement this as observers and we're not going to implement it in many different ways for all flavors. You can write your own observer and add it with the methods named like the events.

If you really do want them on your model: create an observer that does that:

```
class Observer_CallSelf {
    public static function orm_notify($model, $event)
    {
        if (method_exists($model, $event)
        {
            $model->{$event}();
        }
    }
}
```

**Comment by snrp** [comment]
I already added it to my `Base_Model`, I thought it would be a nice adition to the framework too. But if you think its bette this way...

Btw, I added it this way:

```
public function observe($event)
{
    if (method_exists($this, $event))
    {
        $this->{$event}();
    }
    parent::observe($event);
}
```

**Comment by jschreuder** [comment]
That's up to you if you like that better. But that it's possible to make this work using the observer I wrote in 1 minute shows you that the observer pattern is a more powerfull implementation: it's possible to do want you wanted easily, while a lot more complex behavior is possible as well.

**Comment by snrp** [comment]
Hmmm... I think there is a misundestanding.

I did not propose to replace the Observers. 

Rather to make it possible to have a function named (for example) `before_insert()' in a model. Currently that is not possible directly, since you can not make Model_Whatever extend Observer. And therefore you have to use  orm_notify().

**Comment by jschreuder** [comment]
I know you didn't suggest replacing them, but my point was that it's bad programming to implement something in multiple ways: pick your implementation and don't create hugemongous classes and ugly code by catering to everything. Thus I chose the more powerfull implementation which can be easily implemented to allow for another one as I showed.

The observer pattern allows for loads of composition and is incredibly extendible while easy to understand. Your preferred implementation is basicly procedural code. Yes you have to use orm_notify(), because that's how it's meant to work and allows for far more flexibility. Flexible code isn't adding everything you might want, it's allowing everything you might want by composition. The first makes for spagetty code, the second makes for DRY extendeable code.
