### ISSUE TITLE
FR: ORM model before_create observer

### ISSUE THREAD

**Issue by ghost** [fuel/orm#166]
The orm/classes/model __construct has two observers at the moment, _after_ it has loaded its data (either from the database or from a supplied initial array of data). These are after_load and after_create respectively.

I have an instance where I would like to load initial data into fields of the model - some database-linked fields and some not database-linked, e.g. $_myField). This should be done before the orm model loads data over the top.

My request is for a 'before_create' observer to enable this to be done. Maybe this would need to be extended to before_create and a before_load observers, but either way, it is the ability to tweak the model instance, to load default data into it (which may come from config data or other sources) before data is loaded into it.

**Comment by WanWizard** [comment]
Creation happens in the base model constructor.

It doesn't anything other then that, so your model can have it's own constructor, where you can do whatever you want before calling parent::_constructor.

Which includes calling

```
$this->observe('before_create');
```

by which you have created the extra observer.

**Comment by consilience** [comment]
So a "before_create" observer in the orm model is not needed, because I can easily create my own in an overridden __construct()? This is only possible in this case because "before_create" needs to be the very first thing when constructing a model.

If creating custom observers like this, would it be safer (more future-proof) to give it a more unique name, less likely to be used by fuelphp in later versions? "custom_before_create", for example.

**Comment by WanWizard** [comment]
You can safely use 'before_create', as we don't expect major developments on this ORM anymore. It will not be part of the FuelPHP distribution anymore in 2.0 (but we will provide legacy support for ported applications until 2.1).

**Comment by consilience** [comment]
Of course. Thanks.
