### ISSUE TITLE
limit() with related() creates subquery instead of limiting the resultset

### ISSUE THREAD

**Issue by Altreus** [fuel/orm#170]
This is easy to reproduce. Simply use related() on a model to filter your results by a related table, then apply a limit. This is most frequently exhibited for us in get_one, which is implemented by applying a limit.

```
$location = Model_Stock_Location::find()
    ->related('sites')
    ->where('sites.id', $site_id)
    ->limit(1)
    ->get();
```

In this example, the 'sites' relation is a many-to-many on the stock location model. The intent is to find those stock locations associated with the provided site. The limit is added to reproduce the behaviour of get_one(), to show that it is the limit, and not get_one per se, that is to blame.

The expected result is a single Model_Stock_Location. The actual result is null.

The reason for this is that the limit causes a new subquery to be created on the table that Model_Stock_Location represents, to which the LIMIT is then applied. This is useless: the first entry in the stock locations table is not related to the input $site_id. Thus the rest of the query is joined against an artificially-limited subset of the data in the table, and the row is not found.

Expected behaviour is for all data to be produced, and for the result set to be limited afterwards. The current behaviour of limit is itself of limited use and rarely what is intended when one limits a query.

**Comment by WanWizard** [comment]
This is been explained a lot of times, see the forums.

The ORM is not a query builder that blindly joins and limits. The ORM will always make sure the resultset is complete, so if  parent has two children, you will get both children with a limit(1), but never one.

This is by design.

You can use the rows_limit() method to work around it, with the warning that you get incomplete results.
