### ISSUE TITLE
get_one() inconsistent due to behaviour of limit()

### ISSUE THREAD

**Issue by Altreus** [fuel/orm#172]
Since the behaviour of limit() is to limit based on a subquery, this means that any ORM query with a join in it cannot use get_one, because get_one uses limit, and the behaviour of limit is not correct for get_one's purpose.

get_one needs to limit the entire resultset, not the subquery for the model on which the query was started.

**Comment by Altreus** [comment]
This issue is the flipside to issue #170, wherein I was informed that limit's behaviour is intentional

**Comment by WanWizard** [comment]
Fixing this might cause side effects. 

When doing a first or last with related(), it currently returns null if the first (or last) record has no related records. If you change it (to use rows_limit instead of limit), it would return the first or last, but obviously without relations.  Which means any app banking on the old behaviour will break.

**Comment by WanWizard** [comment]
This will allow you to switch from limit (still the default) to rows_limit using the $options array.

```
$users = Model_User::find('first', array('related' => 'group', 'rows_limit' => 1));
```
