### ISSUE TITLE
Orm\BelongsTo needlessly breaks relations on delete

### ISSUE THREAD

**Issue by peter-fritchley** [fuel/orm#199]
What are the advantages of belongs_to to breaking the relations when the object on which it is unsetting foreign keys is the one that is being deleted?

There are situations where this causes exceptions to be thrown when trying to delete the object: "Primary key on model Orm\Model cannot be changed"

There only seems to be a need for this in has_one and has_many (many_many would delete the row in the table_through).

**Comment by WanWizard** [comment]
Can you elaborate on these situations?

Belongs_To only resets the FK, it doesn't touch the PK, so that can't be the cause of that exception.

Having said that, it's seems a bit pointless to set the FK to null, just before deleting the object. On the other hand, it doesn't save that change on a delete, so it shouldn't really have any effect (positive or negative).

**Comment by Altreus** [comment]
we fixed this :)

https://github.com/fuel/orm/pull/241
