### ISSUE TITLE
Orm performance: in general and especially with huge queries

### ISSUE THREAD

**Issue by jeffutter** [fuel/orm#22]
_[Edit by jschreuder]I edited the main topic, any performance related research or follow-up questions should go here for now.[/edit]_

I have a query that has a few nested relations and a couple multi-level nested relations. On a particular page this query returns 1,700 rows. The actual execution time of the query is in the ballpark of .001 ms. However the entire page takes 5-8seconds to load.

I have noticed that the hydrate function gets called about 6,000 times. I am curious if orm isn't catching when objects have already been hydrated and is re-hydrating them?

**Comment by jschreuder** [comment]
We'll have to study the hydration but there's not that much waste in there, I think some stuff can be a little more optimized but I doubt we're talking about something massive. It's possible however there's a loop in there somewhere.

One very, very important point before anything else though: your time measures aren't very meaningfull. What we'd need to have measured is the time it takes to run Model_Example::find() instead of the whole page, using at least 1700 objects (each individual row must have at least 1 unique object, possibly more) has a massive potential for non hydration related slowdowns. The time that executing the query takes is meaningless for comparisson with the entire page load, though it does eliminate that as a potential cause. An interesting measure for comparisson would be to have the DB query builder execute a similar query and return objects.

Based on what you said I'm guessing you're loading in 3 different relations (normal or nested), because for each row retrieved first the base object will taken from it and then the relations will be loaded. All are first put into an array and then used to hydrate a new object instance when the instance wasn't created yet. Thus each hydration() usage doesn't equal a new object, but it has to be run in order to find out if a new subrelation is there.
Thus loading 1700 rows for an object with 3 relations will lead to 4x 1700 loads = 6800 calls to hydration().

I see some options for improvement, though none of them are guaranteed to improve and might even slow things down. And as I said not really anything massive:
- getting rid of some of the class calls, for instance the PK field(s) can be given with the $models array and the implode_pk() method might be possible to run non variably. (use `Model::implode_pk($values, $pk_field_names)` instead of `Model_Example::implode_pk($values)`)
- instead of using cached_objs() we might just check the result array for the imploded PK and possibly do this once only the PKs have been found and before retrieving the entire array
- unsetting used keys from the row array
- using another way to get the field name than preg_replace(), see if using substr() is possible reliably
- do some heavy profiling to check for possible loopings

**Comment by jeffutter** [comment]
The 7ish seconds i mentioned is the time for the Model_Name::find(). I am using profiler with a mark right before the find and a mark right after. I don't have my code exactly in-front of me right now but the find is something like this:

$statuses = Model_Status::find()
->related('jobs')
->related('jobs.store')
->related('jobs.customer')
->related('jobs.payments')
->related('jobs.charges')
->related('jobs.notes')
->related('jobs.notes.user')
->where('jobs.open', true)
->where('jobs.store', Session::get('store_id'))
->get();

**Comment by jschreuder** [comment]
Could you pull and test it again? I made the changes I mentioned above and while it doesn't look like much, the more carefull memory usage and less variable class calls might save some actual time on a massive dataset like yours.

**Comment by jeffutter** [comment]
It seems as though only one row per relation is being fetched. I'm expecting 5-20 'jobs' per 'status' in the above query and now i get one.. That being said it seems a bit quicker (a second or two). however, I think it actually uses more memory (getting about 15mb now).

Last night I wrote out the whole query using a massive DB query. I get fetch and render the page in 0.5 seconds on this machine from DB. I realize ORM will add some overhead, no doubt. But I would expect it to be in the ~1s arena?

**Comment by jschreuder** [comment]
You are right about the single returns, I hadn't noticed that effect of one of the later changes. That may also have had an adverse effect on memory and speed.
Having said that I think it should now use less memory as it's far more efficient (using references and unsetting the used data).

It's hard to say what is reasonable for an Orm without comparing it to something of the same scope (the DB class doesn't compare in any way, it's the basis for the Orm not an alternative in terms of functionality). I don't think any Orm is really meant to work with hugemongous datasets, but I would love if we could make ours efficient enough to do it in a reasonable amount time/memory. Feel free to check the code and let us know if you feel some things could be better, because I'm personally at a loss here - nothing looks like it's wastefull or inefficient. Don't mistake how heavy and complicated something like hydration is.
The amount of time your DB query needs is a baseline. Only once that is done will the Orm start doing its work. And the Orm needs a maximum of 7 objects per row where the DB will do with just one. 15mb actually doesn't even sound that bad for 1700 rows, depending on how much data is in there of course - but you seem to be fetching a lot of info. And like before, it's just a number - you didn't give me anything for comparisson.

**Comment by jeffutter** [comment]
The load times seem to vary quite a bit. I'm either getting around 7 seconds still or up to 13 seconds. As for memory it seems consistently in the 18MB range. The memory usage as a number isn't too big of a deal for me, performance is though.

Using Profiler Marks, around the query, it seems that the Model::find alone is taking about 8 seconds. I'm also foreaching through a bunch of related models that may be adding the extra few seconds.

Would it be helpful if i provided a dump of my DB tables and my Models, Controllers and Views so you can see how it performs for yourself?

**Comment by jschreuder** [comment]
That would be very helpfull, I'm working with a small set of dummy data currently having a massive set would be very usefull.

**Comment by patie** [comment]
Orm is slow with large sets -without relations- too

for examaple i tested prodcuts table with 6000 rows - takes 23secs and 56MB uhh? ok 6000 rows.. in practice not very used selecting 6000 rows but too slow for 500 rows i mean - 600ms and 15MB is too much (=500 ROWS WITHOUT RELATION) tested on clear controller without anything - only calling orm model
im wrong ? Sorry if yes

**Comment by jschreuder** [comment]
Quoting myself:

> I don't think any Orm is really meant to work with hugemongous datasets, but I would love if 
> we could make ours efficient enough to do it in a reasonable amount time/memory. Feel free 
> to check the code and let us know if you feel some things could be better, because I'm 
> personally at a loss here - nothing looks like it's wastefull or inefficient. 

I'll keep looking into more optimizations, but in the end an Orm isn't meant for this. When working with such large datasets you'll probably need a lot of optimizations and not a one-size-fits-all solution. We'll keep looking into this, but I have my doubts on how much better it can be - unless it does turn out there's some waste or a loop somewhere.

**Comment by jschreuder** [comment]
We've just improved the runtime for 1000 rows of a 4 columns table without relations by 33%. I'd be interested to know how much this improves the time/memory of you guys.

I'll be testing with Jeff's dataset to find other possible slowdowns and report back here when I know more.

**Comment by jeffutter** [comment]
With the latest commits I'm seeing query/hydrate times as low as 3s and as high as 9s. Definitely an improvement! Hopefully that dataset will be telling. keep up the good work.

**Comment by jschreuder** [comment]
There's a huge difference between those numbers, is that for the same query or for different queries? And in the latter case: which queries are slower.

If it's for the same query I expect the problem for the 9s is that your testing on your normal computer/laptop? I never do that for speed testing purposes myself because it often differs that wildly, the high numbers will mostly have little to do with the actual test and everything to do with some slowdown by my Windows laptop (because of IDE or some other running process). For that reason I have a linux setup which does give me pretty consistent test results.

**Comment by jeffutter** [comment]
Same query (might have something to do with load on my local box like you mention). Generally it's in the 5s ballpark, but it hit as low as 3s once and as high as 11s a couple times (after a bunch of un-scientific refreshes).

**Comment by patie** [comment]
jschreuder with new developer branch its a lot better

OLD
1 find query -> 500 rows -> 550-800ms / 15.40MB

NEW
1 find query -> 500 rows -> 350-375ms / 12.80MB

(the some query, settings etc. of course :D)

starts to like me, you're really good, yet a little while and it will be super. thanks

**Comment by jschreuder** [comment]
I think @patoman 's results are about what one should expect, about .7 ms per object isn't bad.

Jeff's problem might be related to something else: if you join multiple plural relations you'll end up with the product of the total number of both. Example joining 4 objects and 5 objects on a single parent object will lead to 1 x 4 x 5 = 20 rows to fetch 9 objects. We're thinking about ways to work around this, but you'll always have to do so explicitly probably - I don't think I'll make the orm choose for you (= config over convention as always).

We'll keep testing the performance, but for now I'm closing this issue as I'm not expecting any new data on performance.
