### ISSUE TITLE
Orm\Observer_Validation creates an instance of \Fieldset

### ISSUE THREAD

**Issue by itsa-sh** [fuel/orm#268]
`Orm\Observer_Validation` creates an instance of fieldset with the model class name when one doesn't exist.  Which causes an issue with **Cli**; For the obvious reasons I do not need an instance of \Fieldset (and so I don't create one).

https://github.com/fuel/orm/blob/1.7/develop/classes/observer/validation.php#L79-L82

Above i've highlighted where this issue occurs, if an instance of Fieldset does not exist, an instance is therefore created and ultimately the next time an instance of Model is saved, a validation error occurs.

In my Task I want to import data, I start by:

Creating an instance of Model_Venue `$model = \Venues\Model_Venue::forge()`.

Eventually after defining the properties I save; something similar to:

``` php
$model->name = $data['name'];
$model->some_property = $data['some_property'];

try {
    $model->save();
```

This in turn executes `$this->observe('before_save');`; which finds `Orm\Observer_Validation` (as defined in the `$_observers`); which will try and find a fieldset by the Model name; finally when one is not found, it forges one.

**Comment by WanWizard** [comment]
Well, I personally find the way you express youself "utterly retarded".

`set_fields()`, as the docblock says, "Set a Model's properties as fields on a Fieldset, which will be created with the Model's classname if none is provided". Pretty difficult to create fields on a fieldset of you don't have a fieldset, don't you think?

Futhermore, `set_fields()` is called by the model's `set_form_fields()` method (he, look, there's that word "form" again), which in turn is only called by the Fieldset's `add_model()` method.

So unless you're "utterly retarded" and create a fieldset when in the CLI, what exacty is your problem?

**Comment by WanWizard** [comment]
You could have written that in your original post, and used normal language, and then, perhaps, you would have gotten the proper attention. Given your response apparently manners and normal language use are beyond you, which doesn't really make me want to help you.

But ok. 

If you would have looked a little bit further, in the `validate()` method that `before_save()` calls, you will see that it NEEDS the fieldset in order to run the validation. So removing the code that creates the fieldset would break your validation.

We are very aware that the tangled mess of Fieldset, Validation, and Form is something that needs to be fixed, which is being worked on. But for the moment we can't, because that would break everything that exists, and I'm pretty sure Phil would not like that...
