### ISSUE TITLE
observer  before_find() feature ?

### ISSUE THREAD

**Issue by patie** [fuel/orm#39]
you wonder about before_find or before_read or something like that ? i need execute something before reading but _init load only first time not before each action.

or have other idea ? thanks

**Comment by jschreuder** [comment]
There's no before_find because that can't work on a model instance (there's no instance yet to work with). Why do you need one?

**Comment by patie** [comment]
if I say a specific reason you send me to hell :) As I have previously mentioned - I need not only _connection for model but in loop i need change this _connection.. because i have multilangual project where each lang have own database. dont worry about data, main language has auto_increment and other dont have (something like copy with other datas). (no way this data into one database)

**Comment by jschreuder** [comment]
In that case I'd extend the find() or query() method, I don't see a reason (or even a way) to support this in the core with observers (because the observers work with instantiated models).

This is very specific need which I don't see as something that most will need. That's the kind of thing you have to add yourself, if we cater to everything the whole thing would become ginormous and incredibly slow.

**Comment by patie** [comment]
ok no problem this was only question.. maybe easiest for me will be extend connection method, i try it later. thanks. have a nice day
